# Makefile

MANUSCRIPTS  = Introduction.markdown
MANUSCRIPTS += Preface.markdown
MANUSCRIPTS += Abstract.markdown
MANUSCRIPTS += Conclusion.markdown

CLS = hacett-socsci-thesis.cls
OUT = manuscript.pdf

all: $(OUT) .gitignore

.gitignore: .gitignore.in
	echo '# .gitignore (autogenerated, edit .gitignore.in)'  > $@
	echo							>> $@
	echo '# .tex for manuscripts'				>> $@
	echo $(MANUSCRIPTS:markdown=tex) | tr ' ' '\n'		>> $@
	echo							>> $@
	echo '# from .gitignore.in'				>> $@
	cat $<							>> $@

manuscript.pdf: skel.tex $(MANUSCRIPTS:markdown=tex) bibliography.bib
	latexmk -f -silent -bibtex-cond -lualatex skel.tex
	mv skel.pdf $@

%.tex: %.markdown
	pandoc --biblatex -f markdown -t latex < $< > $@

bibliography.bib: $(MANUSCRIPTS)
	cat $< | ./pandoc-zotxt-bib.pl - > $@

# NOTE: do not remove bibliography.bib and manuscript.pdf, they will be
# checked in.
clean:
	rm -f *.aux *.fdb_latexmk *.fls *.log *.bbl \
		*.bcf *.blg *.out *.run.xml *.toc \
		$(MANUSCRIPTS:markdown=tex) skel.pdf

hygienic:
	rm -f $(OUT) bibliography.bib

.PHONY: clean all hygienic
